# Generated by Django 3.2 on 2021-05-02 17:43

from django.db import migrations, models
import photos.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=photos.models.build_photos_path)),
                ('category', models.CharField(choices=[('people', 'people'), ('animals', 'animals'), ('nature', 'nature & landscapes'), ('weddings', 'weddings')], max_length=8)),
                ('alt_text', models.CharField(max_length=200, verbose_name='Alternate text for visually impaired users')),
                ('caption', models.CharField(max_length=200, verbose_name='Image caption')),
                ('href', models.URLField(blank=True, null=True, verbose_name='Link to original')),
            ],
        ),
    ]
